### ISSUE TITLE
[DEPRECATED] Use of User-Agent param

### ISSUE THREAD

**Issue by soulcodex** [dherran/laravel-rawg#2]
Hi @dherran,

Actually the RAWG api are in proccess to deprecate the User-Agent auth flow to ApiKey, Do you have planned make this changes or will you accept a PR?

Thanks

**Comment by dherran** [comment]
I would happily accept a PR :)

**Comment by dherran** [comment]
Fixed in https://github.com/dherran/laravel-rawg/commit/5621b19830f31b057c630be4ffd0d417e1478565
